name: PHP

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOCOMMIT_PAT }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Composer Install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: NPM Install and Build
        run: |
          npm install
          npm run production
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Get Changed PHP Files
        id: changed-php-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.php
      - name: Launch Pint inspection
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && steps.changed-php-files.outputs.any_changed == 'true'
        run: vendor/bin/pint ${{ steps.changed-php-files.outputs.all_changed_files }}
      - name: Commit Pint Inspection Changes
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Pint Reformatting"
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
